### ISSUE TITLE
LDAP extension breaking CKAN since upgrade from 2.7 to 2.8

### ISSUE THREAD

**Issue by ted-strauss-K1** [NaturalHistoryMuseum/ckanext-ldap#40]
Since upgrading CKAN to 2.8 I get internal server error on several pages; attaching apache error log.

Seems to be related to this: https://github.com/ckan/ckan/issues/3921

```
[Wed Jul 11 15:11:59.527347 2018] [:error] [pid 6098] [remote 127.0.0.1:20335] [2018-07-11 15:11:59,525] ERROR in app: Exception on /user/login [GET]
[Wed Jul 11 15:11:59.527395 2018] [:error] [pid 6098] [remote 127.0.0.1:20335] Traceback (most recent call last):
[Wed Jul 11 15:11:59.527406 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
[Wed Jul 11 15:11:59.527415 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     response = self.full_dispatch_request()
[Wed Jul 11 15:11:59.527424 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
[Wed Jul 11 15:11:59.527432 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     rv = self.handle_user_exception(e)
[Wed Jul 11 15:11:59.527441 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
[Wed Jul 11 15:11:59.527449 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     reraise(exc_type, exc_value, tb)
[Wed Jul 11 15:11:59.527458 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
[Wed Jul 11 15:11:59.527493 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     rv = self.preprocess_request()
[Wed Jul 11 15:11:59.527502 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
[Wed Jul 11 15:11:59.527510 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     rv = func()
[Wed Jul 11 15:11:59.527517 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 281, in ckan_before_request
[Wed Jul 11 15:11:59.527525 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     identify_user()
[Wed Jul 11 15:11:59.527532 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/src/ckan/ckan/views/__init__.py", line 100, in identify_user
[Wed Jul 11 15:11:59.527539 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     item.identify()
[Wed Jul 11 15:11:59.527547 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/plugin.py", line 129, in identify
[Wed Jul 11 15:11:59.527554 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     user = pylons.session.get('ckanext-ldap-user')
[Wed Jul 11 15:11:59.527562 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
[Wed Jul 11 15:11:59.527570 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     return getattr(self._current_obj(), attr)
[Wed Jul 11 15:11:59.527577 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
[Wed Jul 11 15:11:59.527595 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     'thread' % self.____name__)
[Wed Jul 11 15:11:59.527604 2018] [:error] [pid 6098] [remote 127.0.0.1:20335] TypeError: No object (name: session) has been registered for this thread
[Wed Jul 11 15:11:59.527777 2018] [:error] [pid 6098] [remote 127.0.0.1:20335] mod_wsgi (pid=6098): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Wed Jul 11 15:11:59.527818 2018] [:error] [pid 6098] [remote 127.0.0.1:20335] Traceback (most recent call last):
[Wed Jul 11 15:11:59.527842 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
[Wed Jul 11 15:11:59.527944 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     return self.apps[app_name](environ, start_response)
[Wed Jul 11 15:11:59.527972 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
[Wed Jul 11 15:11:59.528143 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     app_iter = app(environ, wrapper.wrap_start_response)
[Wed Jul 11 15:11:59.528175 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Wed Jul 11 15:11:59.528387 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     resp = self.call_func(req, *args, **self.kwargs)
[Wed Jul 11 15:11:59.528418 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Wed Jul 11 15:11:59.528448 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     return self.func(req, *args, **kwargs)
[Wed Jul 11 15:11:59.528472 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
[Wed Jul 11 15:11:59.528627 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     return request.get_response(self.app)
[Wed Jul 11 15:11:59.528683 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Wed Jul 11 15:11:59.529195 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     application, catch_exc_info=False)
[Wed Jul 11 15:11:59.529227 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Wed Jul 11 15:11:59.529256 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     app_iter = application(self.environ, start_response)
[Wed Jul 11 15:11:59.529280 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
[Wed Jul 11 15:11:59.529307 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     resp = self.call_func(req, *args, **self.kwargs)
[Wed Jul 11 15:11:59.529324 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
[Wed Jul 11 15:11:59.529347 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     return self.func(req, *args, **kwargs)
[Wed Jul 11 15:11:59.529372 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
[Wed Jul 11 15:11:59.529476 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     response = request.get_response(self.app)
[Wed Jul 11 15:11:59.529506 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
[Wed Jul 11 15:11:59.529542 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     application, catch_exc_info=False)
[Wed Jul 11 15:11:59.529566 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
[Wed Jul 11 15:11:59.529591 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     app_iter = application(self.environ, start_response)
[Wed Jul 11 15:11:59.529607 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
[Wed Jul 11 15:11:59.529631 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     return self.wsgi_app(environ, start_response)
[Wed Jul 11 15:11:59.529662 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
[Wed Jul 11 15:11:59.529798 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     return self.wrap_app(environ, session_start_response)
[Wed Jul 11 15:11:59.529851 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
[Wed Jul 11 15:11:59.529883 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     response = self.handle_exception(e)
[Wed Jul 11 15:11:59.529909 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
[Wed Jul 11 15:11:59.529934 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     return self.finalize_request(handler(e), from_error_handler=True)
[Wed Jul 11 15:11:59.529954 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/flask_app.py", line 411, in error_handler
[Wed Jul 11 15:11:59.529980 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     extra_vars = {u'code': e.code, u'content': e.description}
[Wed Jul 11 15:11:59.530016 2018] [:error] [pid 6098] [remote 127.0.0.1:20335] AttributeError: 'exceptions.TypeError' object has no attribute 'code'
```

**Comment by jrdh** [comment]
Hi @tedstrauss, thanks for raising this. It might be worth your time to have a look at https://github.com/NaturalHistoryMuseum/ckanext-ldap/pull/31 and see whether that resolves your issues. As @alycejenni says on the PR we're in the process of upgrading all of our plugins to 2.8 compatibility but it's a large task.

**Comment by ted-strauss-K1** [comment]
I checked out the branch and restarted apache, and am getting the same errors.
Would I need to run setup.py first?

**Comment by lucasbenevides** [comment]
I had the exact same issue. Error in 
`File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/plugin.py", line 129, in identify
[Wed Jul 11 15:11:59.527554 2018] [:error] [pid 6098] [remote 127.0.0.1:20335]     user = pylons.session.get('ckanext-ldap-user')`

Is there already any answer?

**Comment by alycejenni** [comment]
@lucasbenevides have you checked out the `ckan-upgrade-2.8.0a` branch? That error is referencing the current master branch, which isn't compatible with CKAN 2.8.

EDIT: Actually, I've just re-read the error messages from @tedstrauss as well and the same line appears. If you haven't already then I'd try running `setup.py` because it clearly hasn't installed properly - there shouldn't be any references to pylons in the new branch.

**Comment by lucasbenevides** [comment]
Yes @alycejenni , thank you, I did apply that upgrade and it worked ( although I am still having LDAP server credentials error). It is tricky to get some not commited pull request, but the link https://help.github.com/articles/checking-out-pull-requests-locally/ helped me.  Thank you!

**Comment by lucasbenevides** [comment]
I am having a different error, sometimes it works and sometimes it doesn't. 
Explaning better: the first time I access the portal, it gives Internal Server Error. If I refresh the page in the browser it works. The exception that works the first time is below:

`Exception: The auth u'user_create' is not found for chained auth
[Wed Sep 26 16:59:37.943167 2018] [wsgi:error] [pid 1425:tid 140225646978816] [remote 127.0.0.1:0] mod_wsgi (pid=1425): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
[Wed Sep 26 16:59:37.943287 2018] [wsgi:error] [pid 1425:tid 140225646978816] [remote 127.0.0.1:0] Traceback (most recent call last):
[Wed Sep 26 16:59:37.943401 2018] [wsgi:error] [pid 1425:tid 140225646978816] [remote 127.0.0.1:0]   File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
[Wed Sep 26 16:59:37.943519 2018] [wsgi:error] [pid 1425:tid 140225646978816] [remote 127.0.0.1:0]     return self.apps[app_name](environ, start_response)
[Wed Sep 26 16:59:37.943622 2018] [wsgi:error] [pid 1425:tid 140225646978816] [remote 127.0.0.1:0]   File "/usr/lib/ckan/default/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
[Wed Sep 26 16:59:37.944215 2018] [wsgi:error] [pid 1425:tid 140225646978816] [remote 127.0.0.1:0]     app_iter = app(environ, wrapper.wrap_start_response)`

**Comment by alycejenni** [comment]
I've come across this when upgrading as well - unfortunately it's a limitation in the main CKAN code. There's a PR open that fixes it: ckan/ckan#4248
ckan/ckan#4249 may also help :)

**Comment by lucasbenevides** [comment]
Thank you again alycejenni, it seems that error has stopped.

But another intriguing thing is happening: when I try to logout, clicking in the door button in the upper right icon, sometimes it doesn't work, it keeps my domain account logged on.  Is accesses user/logged_out_redirect but my user keeps logged in. Do you know how to fix it?

**Comment by boykoc** [comment]
@lucasbenevides @alycejenni With a **different SSO extension** I've run into what sounds like a similar issue. After upgrading to 2.8.x I've found it doesn't logout properly. Actually it's after the second logout attempt IAuthenticator's `logout()` isn't called according to my logs / debugging...seems to pull the cached response only unless you wait till your settings clear it. But if you remove the cache settings on the deployment it appears to work (or use paster for dev).  

I'm still digging to better understand this, as in my case this isn't really a work-around.

**Comment by actongorton** [comment]
@boykoc I'm currently trying to debug this issue. Have you found any solutions?

**Comment by boykoc** [comment]
@actongorton Nothing solid unfortunately.  But this sounds similar to issue #53.  

I'm not 100% sure but it seems in CKAN 2.8 caching was modified a bit. I've had a hard time tracking it down to be sure though.  I'm kind of suspecting that new Flask blueprints aren't using the same cache setup as the older pylons controllers do/did.  If i'm right, which again i'm not sure yet, most extensions using some form of their own authentication with a caching server (maybe even ckan default authentication?) might be missing the `cache-control: no-store` headers on some requests, letting second requests pull the cached results and essentially bypass authentication or switch the user. Users can't logout because the application is getting cached responses with the authenticated user.  

I found this comment in the CKAN codebase which might support this? https://github.com/ckan/ckan/blob/d7efea1d0e2729b22dd8377d3fcc9177ae69853b/ckan/lib/base.py#L204

**Comment by alycejenni** [comment]
The master branch is now updated to work with CKAN 2.8+, so I'm closing this issue.
