### ISSUE TITLE
Help getting ldap working

### ISSUE THREAD

**Issue by avowkind** [NaturalHistoryMuseum/ckanext-ldap#51]
Hi, I am trying to integrate this extension into our ckan build which is based on the docker_ckan setup using docker-compose.  All requirements appear to be installed and ldap is added to the plugins list with appropriate configs (below).  start up is ok with no errors from the ldap module.  However, when I load a page I get an exception at the call identify
    user = pylons.session.get('ckanext-ldap-user')
This is before I can get to the login page. 
Its curious that this var is being requested during page load as it is not set until 
All suggestions welcome. 

```
Exception happened during processing of request from ('127.0.0.1', 42604)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "/usr/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
    return self.apps[app_name](environ, start_response)
  File "/usr/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/srv/app/src/ckan/ckan/config/middleware/flask_app.py", line 286, in ckan_before_request
    identify_user()
  File "/srv/app/src/ckan/ckan/views/__init__.py", line 100, in identify_user
    item.identify()
  File "/srv/app/src/ckanext-ldap/ckanext/ldap/plugin.py", line 129, in identify
    user = pylons.session.get('ckanext-ldap-user')
  File "/usr/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
  File "/usr/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
    'thread' % self.____name__)
TypeError: No object (name: session) has been registered for this thread
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 42612)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/paste/httpserver.py", line 1068, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/lib/python2.7/site-packages/paste/httpserver.py", line 442, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/site-packages/paste/httpserver.py", line 437, in handle_one_request
    self.wsgi_execute()
  File "/usr/lib/python2.7/site-packages/paste/httpserver.py", line 287, in wsgi_execute
    self.wsgi_start_response)
  File "/srv/app/src/ckan/ckan/config/middleware/__init__.py", line 202, in __call__
    return self.apps[app_name](environ, start_response)
  File "/usr/lib/python2.7/site-packages/repoze/who/middleware.py", line 86, in __call__
    app_iter = app(environ, wrapper.wrap_start_response)
  File "/usr/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fanstatic/publisher.py", line 234, in __call__
    return request.get_response(self.app)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/site-packages/webob/dec.py", line 147, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/usr/lib/python2.7/site-packages/webob/dec.py", line 208, in call_func
    return self.func(req, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fanstatic/injector.py", line 54, in __call__
    response = request.get_response(self.app)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1053, in get_response
    application, catch_exc_info=False)
  File "/usr/lib/python2.7/site-packages/webob/request.py", line 1022, in call_application
    app_iter = application(self.environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/beaker/middleware.py", line 156, in __call__
    return self.wrap_app(environ, session_start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/srv/app/src/ckan/ckan/config/middleware/flask_app.py", line 286, in ckan_before_request
    identify_user()
  File "/srv/app/src/ckan/ckan/views/__init__.py", line 100, in identify_user
    item.identify()
  File "/srv/app/src/ckanext-ldap/ckanext/ldap/plugin.py", line 129, in identify
    user = pylons.session.get('ckanext-ldap-user')
  File "/usr/lib/python2.7/site-packages/paste/registry.py", line 137, in __getattr__
    return getattr(self._current_obj(), attr)
  File "/usr/lib/python2.7/site-packages/paste/registry.py", line 197, in _current_obj
    'thread' % self.____name__)
TypeError: No object (name: session) has been registered for this thread
```

LDAP access from inside the container is working I can call 
`ldapsearch  -x -h ldap.example.co.nz -p 389  -w "secret" -D "username@example.co.nz" -b "ou=pfr users,dc=pfr,dc=co,dc=nz" -s sub "(sn=watkins)" sAMAccountName`
and get the correct result.

Config is 
```
## LDAP settings
# The URI of the LDAP server, of the form ldap://example.com. 
# You can use the URI to specify TLS (use 'ldaps' protocol), 
# and the port number (suffix ':port');
ckanext.ldap.uri = ldap://ldap.example.co.nz:389
# The base dn in which to perform the search. 
ckanext.ldap.base_dn = ou=example users,dc=example,dc=co,dc=nz
# This is the search string that is sent to the LDAP server, 
# in which '{login}' is replaced by the user name provided by the user.
# Example: 'sAMAccountName={login}'. 
# The search performed here must return exactly 0 or 1 entry. 
# See ckanext.ldap.search.alt to provide search on alternate fields;
ckanext.ldap.search.filter = sAMAccountName={login}
# The LDAP attribute that will be used as the CKAN username. This must be unique;
ckanext.ldap.username = sAMAccountName
# The LDAP attribute to map to the user's email address. This must be unique.
ckanext.ldap.email = email
#: If your LDAP server requires authentication (eg. Active Directory), this should be the DN to use;
ckanext.ldap.auth.dn = username@example.co.nz
# : If your LDAP server requires authentication, add the password here;
ckanext.ldap.auth.password = secret
# : This is the method of authentication to use, can be either SIMPLE or SASL;
ckanext.ldap.auth.method = SIMPLE
# use CKAN users if no LDAP user found
ckanext.ldap.ckan_fallback = true
```

**Comment by jrdh** [comment]
Hi @avowkind, I assume as you've closed this you resolved the problem?

**Comment by avowkind** [comment]
Hi Josh, 
Sorry I closed it because I inadvertently created a duplicate.
Just noticed this morning that my issue was reported before as #40. 
I’ve just switched to the new branch and things appear to be working better - I now have another problem but that’s probably just configuration.

Thanks Andrew
