### ISSUE TITLE
setup-org fails ({'identifier': ['Missing value']})

### ISSUE THREAD

**Issue by LucaPrete** [NaturalHistoryMuseum/ckanext-ldap#57]
Hello everyone,

We've been using your plugin for quite a while, with no issues at all. First of all, thank you for creating and maintaining it.

After some time we had the need to rebuild the CKAN containers we're using, and with it reinstall/reconfigure the plugin.

Unfortunately, running the command

```
paster --plugin=ckanext-ldap ldap setup-org -c /etc/ckan/default/ckan.ini
```

we get the following exception:

```
Traceback (most recent call last):
  File "/usr/bin/paster", line 10, in <module>
    sys.exit(run())
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 102, in run
    invoke(command, command_name, options, args[1:])
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 141, in invoke
    exit_code = runner.run(args)
  File "/usr/lib/python2.7/site-packages/paste/script/command.py", line 236, in run
    result = self.command()
  File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/commands/ldap.py", line 44, in command
    self.setup_org()
  File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/commands/ldap.py", line 58, in setup_org
    toolkit.get_action('organization_create')(self.context, {'id': organization_id, 'name': organization_id})
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py", line 431, in wrapped
    result = _action(context, data_dict, **kw)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 855, in organization_create
    return _group_or_org_create(context, data_dict, is_org=True)
  File "/usr/lib/ckan/default/src/ckan/ckan/logic/action/create.py", line 647, in _group_or_org_create
    raise ValidationError(errors)
ckan.logic.ValidationError: {'identifier': ['Missing value']}
```

Any idea what this could mean?

FYI we're using CKAN 2.6.4, and we've already opened an issue on the official CKAN GitHhub, here: https://github.com/ckan/ckan/issues/4861

Thank you for any help.

Cheers

**Comment by alycejenni** [comment]
At the time this issue was opened, this plugin targeted CKAN 2.3a, so this might have been a compatibility issue. It's now updated to work with 2.9a+, so hopefully this isn't a problem anymore - if it is, please reopen this issue!
