### ISSUE TITLE
Error alfer intalling this plugin

### ISSUE THREAD

**Issue by orencio** [NaturalHistoryMuseum/ckanext-ldap#72]
**Description**
I've installed in my system:

```
# python -V
Python 2.7.16
# uname -a
Linux oraobserver 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
# dpkg -l "*ckan*"
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre         Versión           Arquitectura Descripción
+++-==============-=================-============-=====================================================================================
ii  python-ckan    2.9.2-py2-bionic1 amd64        CKAN is an open-source DMS (data management system) for powering data hubs and data p
# dpkg -l python-ldap libldap2-dev libsasl2-dev libssl-dev python-dev
Deseado=desconocido(U)/Instalar/eliminaR/Purgar/retener(H)
| Estado=No/Inst/ficheros-Conf/desempaqUetado/medio-conF/medio-inst(H)/espera-disparo(W)/pendienTe-disparo
|/ Err?=(ninguno)/requiere-Reinst (Estado,Err: mayúsc.=malo)
||/ Nombre             Versión               Arquitectura Descripción
+++-==================-=====================-============-=====================================================================
ii  libldap2-dev:amd64 2.4.47+dfsg-3+deb10u6 amd64        OpenLDAP development libraries
ii  libsasl2-dev       2.1.27+dfsg-1+deb10u1 amd64        Cyrus SASL - development files for authentication abstraction library
ii  libssl-dev:amd64   1.1.1d-0+deb10u5      amd64        Secure Sockets Layer toolkit - development files
ii  python-dev         2.7.16-1              amd64        header files and a static library for Python2
ii  python-ldap:amd64  3.1.0-2               amd64        LDAP interface module for Python
```
I've installed doing this:

```
# cd /usr/lib/ckan/default/src/
# git clone https://github.com/NaturalHistoryMuseum/ckanext-ldap.git
# . /usr/lib/ckan/default/bin/activate
(default) # python -V
Python 2.7.17
(default) # cd ckanext-ldap/
(default) # pip install -r requirements.txt
(default) # python setup.py develop
...
Finished processing dependencies for ckanext-ldap==3.0.0
```

But now ckan doesn't run:

```
==> /var/log/ckan/ckan-worker.stderr.log <==
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/ldap/plugin.py", line 11, in <module>
    from ckanext.ldap import routes, cli
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/ldap/routes/__init__.py", line 7, in <module>
    from . import login
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/ldap/routes/login.py", line 11, in <module>
    from ckanext.ldap.lib.search import find_ldap_user
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/ldap/lib/search.py", line 39
    log.error(f'SASL mechanism not supported: '
                                              ^
SyntaxError: invalid syntax
```

Other example:

```
# ckan -c /etc/ckan/default/ckan.ini ldap setup-org
2021-03-21 10:15:19,629 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2021-03-21 10:15:19,629 INFO  [ckan.config.environment] Loading static files from public
2021-03-21 10:15:19,668 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
...
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/ckanext/ldap/lib/search.py", line 39
    log.error(f'SASL mechanism not supported: '
                                              ^
SyntaxError: invalid syntax
```

**Your Setup**
 - CKAN version: 2.9.2-py2-bionic1
 - Commit/version of this repo: commit afded53f0ae8ba9744a9e9f4aa9bf8944eb88895 (HEAD -> main, tag: v3.0.0, origin/main, origin/HEAD), Merge: 3f3cfae 45ac4d3

What is the problem?

Regards.

**Comment by alycejenni** [comment]
v3.0.0 dropped support for Python 2. The [previous release](https://github.com/NaturalHistoryMuseum/ckanext-ldap/releases/tag/v2.0.0-alpha) _might_ work, but it's for an older version of CKAN so it also might not.

**Comment by jrdh** [comment]
If that doesn't work you should be able to run CKAN 2.9.1 (at least) on this tag: https://github.com/NaturalHistoryMuseum/ckanext-ldap/releases/tag/v2.1.0
