### ISSUE TITLE
"Internal Server Error" on the UI when logging in.

### ISSUE THREAD

**Issue by nfabas** [NaturalHistoryMuseum/ckanext-ldap#78]
**Description**

I am using CKAN 2.9.2 on Ubuntu 20. I followed the instructions but cannot login as any of the user in the LDAP-Database. Instead, I get an "Internal Server Error" on the UI.

**Expected Behaviour**
An LDAP-User should be able to login.

**Error Log**
Here is from the uwsgi logs:

```
Traceback (most recent call last):
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/routes/login.py", line 35, in login_handler
    ldap_user_dict = find_ldap_user(login)
  File "/usr/lib/ckan/default/src/ckanext-ldap/ckanext/ldap/lib/search.py", line 25, in find_ldap_user
    cnx = ldap.initialize(toolkit.config['ckanext.ldap.uri'], bytes_mode=False,
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/python_ldap-3.0.0-py3.8-linux-x86_64.egg/ldap/functions.py", line 85, in initialize
    return LDAPObject(uri,trace_level,trace_file,trace_stack_limit,bytes_mode)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/python_ldap-3.0.0-py3.8-linux-x86_64.egg/ldap/ldapobject.py", line 104, in __init__
    self._l = ldap.functions._ldap_function_call(ldap._ldap_module_lock,_ldap.initialize,uri)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/python_ldap-3.0.0-py3.8-linux-x86_64.egg/ldap/functions.py", line 55, in _ldap_function_call
    result = func(*args,**kwargs)
ldap.LDAPError: (0, 'Error')
```

**Your Setup**
 - CKAN version: 2.9.2
 - Commit/version of this repo: 3.0.0
 - Browser (if relevant): Firefox

**Comment by alycejenni** [comment]
Hi! This looks like an error coming from LDAP, so have you double-checked all your [configuration settings](https://github.com/NaturalHistoryMuseum/ckanext-ldap#configuration)?

**Comment by nfabas** [comment]
Here is my config. 

```
ckanext.ldap.uri = someuri.com
ckanext.ldap.base_dn = ou=example,ou=services,dc=comp,dc=org,dc=com
ckanext.ldap.search.filter = cn=*{login}*
ckanext.ldap.username = cn
ckanext.ldap.email = mail
ckanext.ldap.auth.password = ###
ckanext.ldap.debug_level = 255
```

I suspect this might have to do with this other issue #74 but I am not sure. I don't know how to debug that.

**Comment by alycejenni** [comment]
You need to add the `ldap://` or `ldaps://` prefix to the URI :)

**Comment by nfabas** [comment]
This is a fake URI but still it is missing from the real one. Thank for the tip!
