### ISSUE TITLE
ckan.plugins.core.PluginNotFoundException: ldap

### ISSUE THREAD

**Issue by mrmm2021** [NaturalHistoryMuseum/ckanext-ldap#79]
Hi,

I installed ckan 2.9 on Ubuntu 20.04 with python3 (system default) 
The ldap plugin was installed following the instructions here, but ckan does not works after add ldap in the plugins list in ckan.ini:

```
2021-08-12 11:48:23,509 INFO  [ckan.cli] Using configuration file /etc/ckan/default/ckan.ini
2021-08-12 11:48:23,509 INFO  [ckan.config.environment] Loading static files from public
2021-08-12 11:48:23,568 INFO  [ckan.config.environment] Loading templates from /usr/lib/ckan/default/src/ckan/ckan/templates
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 11, in <module>
    load_entry_point('ckan', 'console_scripts', 'ckan')()
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1212, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 1630, in handle_parse_result
    value = invoke_param_callback(self.callback, ctx, self, value)
  File "/usr/lib/ckan/default/lib/python3.8/site-packages/click/core.py", line 123, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 102, in _init_ckan_config
    ctx.obj = CkanCommand(value)
  File "/usr/lib/ckan/default/src/ckan/ckan/cli/cli.py", line 52, in __init__
    self.app = make_app(self.config)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 123, in load_environment
    p.load_all()
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 165, in load_all
    load(*plugins)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 179, in load
    service = _get_service(plugin)
  File "/usr/lib/ckan/default/src/ckan/ckan/plugins/core.py", line 282, in _get_service
    raise PluginNotFoundException(plugin_name)
ckan.plugins.core.PluginNotFoundException: ldap
```

Searching  for answers I can read about activate the virtualenv for python3 but ths installation is done with python 3 system default.

Any help please?

**Comment by jrdh** [comment]
Hi @mrmm2021 - I just launched a VM and tried this out and it worked for me so I'm guessing you've missed something during your installation. Can you confirm you installed `ckanext-ldap` into the same Python 3 install as `ckan` itself? E.g. when I run `pip3 freeze` on my base Ubuntu 20.04 install I can see `ckan` and `ckanext-ldap` in there, do `ckan` and `ckanext-ldap` appear in there for you too?

**Comment by mrmm2021** [comment]
Hi jrdh,

The problem was beetween python3-ckan (virtualenv) and python3 system default.
ckan always use your own python3 instead system default, I thought  ckan "package installation" on ubuntu would use
python3 system default, but it's not like that

in other words: virtualenv must be activated. 

Thank you!
